"""Mask acceptance: generated masks must survive the REAL gdalwarp.

Three layers of coverage:

1. Golden: for three ref-volume sheets plus a regression sheet whose historical recorded
   mask passed every static validity check yet failed the real cutline warp, the mask
   generated by detect_page_bounds plus the recorded-GCP affine must be accepted by an
   actual ``gdalwarp`` cutline dry-run against its own sheet.
2. Unit: split_overlaps (bisector split, sliver skip, three-cell corner closure, order
   independence) and heal (ladder with an injected acceptance; hopeless inputs return None).
3. The dry-run verdict demonstrably comes from gdalwarp, not shapely ``is_valid``: a
   shapely-valid polygon GDAL rejects returns False, while a hostile spike it tolerates
   returns True.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from shapely.geometry import Polygon, box
from shapely.ops import unary_union

from autogeoref.affine import fit_affine, gcps_from_geojson
from autogeoref.mask.geometry import detect_page_bounds, heal, mask_polygon_4326, split_overlaps
from autogeoref.warp import (
    attach_gcps_vrt,
    gcps_from_feature_collection,
    gdalwarp_cutline_dryrun,
)

pytestmark = [pytest.mark.golden, pytest.mark.gdal]

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures"
REGIONS_DIR = FIXTURES / "ref-volume" / "regions"

REF_SLUGS = [
    "chicago_ill_1895_vol_16_p2",
    "chicago_ill_1895_vol_16_p39",
    "chicago_ill_1895_vol_16_p78",
]
P84_SLUG = "chicago_ill_1912_vol_4_p84"
P84_IMAGE = FIXTURES / "sanborn01790_021" / "regions" / f"{P84_SLUG}.jpg"
P84_RESULT = FIXTURES / "sanborn01790_021" / "results" / "p84.json"

MASK_CASES = [*REF_SLUGS, P84_SLUG]


def _case_inputs(slug: str, ground_truth_path: Path) -> tuple[Path, dict[str, Any]]:
    """(image path, GCP FeatureCollection) for a mask case."""
    if slug == P84_SLUG:
        if not P84_IMAGE.is_file():
            pytest.skip(f"{P84_IMAGE} not present")
        with P84_RESULT.open() as f:
            return P84_IMAGE, json.load(f)["gcps_geojson"]
    image = REGIONS_DIR / f"{slug}.jpg"
    if not image.is_file():
        pytest.skip(f"{image} not present")
    with ground_truth_path.open() as f:
        layers = json.load(f)
    return image, next(x["gcps_geojson"] for x in layers if x["slug"] == slug)


@pytest.fixture(scope="module")
def vrt_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    return tmp_path_factory.mktemp("t6_vrts")


@pytest.fixture(scope="module")
def sheet_vrt_cache() -> dict[str, Path]:
    return {}


def _sheet_vrt(
    slug: str, image: Path, fc: dict[str, Any], vrt_dir: Path, cache: dict[str, Path]
) -> Path:
    """GCP-attached VRT of the sheet — the georeferenced dry-run source."""
    if slug not in cache:
        gcps = gcps_from_feature_collection(fc)
        cache[slug] = attach_gcps_vrt(image, gcps, vrt_dir / f"{slug}.vrt")
    return cache[slug]


# ---------------------------------------------------------------- golden ----


@pytest.mark.parametrize("slug", MASK_CASES)
def test_generated_mask_survives_real_cutline_dryrun(
    slug: str, ground_truth_path: Path, vrt_dir: Path, sheet_vrt_cache: dict[str, Path]
) -> None:
    """detect_page_bounds -> GCP-affine mask -> the REAL gdalwarp must take it.

    For p84 the affine comes from the recorded auto-GCP result: the
    historical failing mask geometry was never exported, so the
    contract here is that OUR generated mask passes the real dry-run on that
    historically problematic sheet.
    """
    image, fc = _case_inputs(slug, ground_truth_path)
    rect = detect_page_bounds(image)
    x0, y0, x1, y1 = rect
    assert 0 <= x0 < x1 and 0 <= y0 < y1, f"degenerate page rect {rect}"

    affine = fit_affine(gcps_from_geojson(fc))
    mask = mask_polygon_4326(rect, affine)
    vrt = _sheet_vrt(slug, image, fc, vrt_dir, sheet_vrt_cache)
    assert gdalwarp_cutline_dryrun(vrt, mask), f"{slug}: gdalwarp rejected generated mask"


# ------------------------------------------------------ split_overlaps ----


def test_split_overlaps_bisector_cut() -> None:
    """Two overlapping rectangles become disjoint, each keeping its centroid side."""
    a = box(0.0, 0.0, 200.0, 100.0)
    b = box(180.0, 0.0, 380.0, 100.0)
    out = split_overlaps({"a": a, "b": b})
    new_a, new_b = out["a"], out["b"]
    assert new_a.intersection(new_b).area < 1e-6
    assert new_a.contains(a.centroid)
    assert new_b.contains(b.centroid)
    # the cut is the perpendicular bisector between centroids (x = 190)
    assert new_a.bounds[2] == pytest.approx(190.0, abs=0.1)
    assert new_b.bounds[0] == pytest.approx(190.0, abs=0.1)
    # nothing lost beyond the shared strip
    assert new_a.union(new_b).area == pytest.approx(a.union(b).area, rel=1e-6)


# Three mutually overlapping masks whose three-cell corner the pairwise
# sequential splitter left uncovered: it cut each pair against geometry earlier
# trims had already moved, so the corner did not close (a 706.7 m^2 hole here,
# and cells that moved by 1107.9 m^2 when the pages were renumbered; 615.7 m^2
# in `_024`, a visible black notch in the served mosaic). Measured in
# `` section 3.
CORNER_MASKS = {
    "v_p1": box(3.0, 64.0, 290.0, 323.0),
    "v_p2": box(250.0, 213.0, 550.0, 441.0),
    "v_p3": box(255.0, 251.0, 476.0, 545.0),
}


def test_split_overlaps_closes_three_cell_corners() -> None:
    """The split partitions the masks: no hole, no double coverage."""
    out = split_overlaps(CORNER_MASKS)
    before = unary_union(list(CORNER_MASKS.values()))
    after = unary_union(list(out.values()))
    assert before.difference(after).area < 1e-6, "the split left ground uncovered"
    slugs = list(out)
    for i, a in enumerate(slugs):
        for b in slugs[i + 1 :]:
            assert out[a].intersection(out[b]).area < 1e-6


def test_split_overlaps_usable_guard_refuses_one_cut_not_all_of_them() -> None:
    """A sheet swallowed by its neighbours must still yield what it can.

    ``_usable`` is a per-neighbour guard on the running cell: shedding more
    than half cumulatively is allowed, taking half of what is LEFT in one cut
    is not. Checking the union of the cuts instead makes a single oversized
    neighbour keep the sheet's WHOLE mask while the neighbours trim themselves
    against it — one-sided, and worth 221902 m2 of double coverage in `_019`
    alone (`` section 3).
    """
    # p2 sits inside three larger neighbours and loses ~3/4 of itself, in
    # quarters that are each legal on their own
    masks = {
        "v_p1": box(-100.0, 0.0, 150.0, 100.0),
        "v_p2": box(0.0, 0.0, 200.0, 200.0),
        "v_p3": box(50.0, 100.0, 300.0, 200.0),
        "v_p4": box(-100.0, 100.0, 150.0, 300.0),
    }
    out = split_overlaps(masks)
    assert out["v_p2"].area < 0.5 * masks["v_p2"].area, "the cumulative trim was refused"
    slugs = list(out)
    for i, a in enumerate(slugs):
        for b in slugs[i + 1 :]:
            assert out[a].intersection(out[b]).area < 1e-6, f"{a}/{b} double coverage"


def test_split_overlaps_does_not_depend_on_page_order() -> None:
    """Relabelling the same geometry must not move a single cutline.

    Cell edges are half-planes between the ORIGINAL centroids, so the sheet a
    piece of ground goes to is decided by geometry alone. Under the sequential
    splitter this arrangement's cells moved by up to 1107.9 m^2 when the pages
    were renumbered.
    """
    shapes = list(CORNER_MASKS.values())
    n = len(shapes)
    forward = split_overlaps({f"v_p{i + 1}": s for i, s in enumerate(shapes)})
    reverse = split_overlaps({f"v_p{n - i}": s for i, s in enumerate(shapes)})
    for i in range(n):
        drift = forward[f"v_p{i + 1}"].symmetric_difference(reverse[f"v_p{n - i}"]).area
        assert drift < 1e-6


def test_split_overlaps_ignores_sliver_overlap() -> None:
    """Overlaps under 25 m^2 are slivers and must be left untouched."""
    a = box(0.0, 0.0, 100.0, 100.0)
    b = box(96.0, 96.0, 200.0, 200.0)  # 4 x 4 = 16 m^2 < 25
    out = split_overlaps({"a": a, "b": b})
    assert out["a"].equals(a)
    assert out["b"].equals(b)


def test_split_overlaps_no_overlap_is_identity() -> None:
    a = box(0.0, 0.0, 100.0, 100.0)
    b = box(500.0, 0.0, 600.0, 100.0)
    out = split_overlaps({"a": a, "b": b})
    assert out["a"].equals(a)
    assert out["b"].equals(b)


# ------------------------------------------------------------------ heal ----

# an invalid bowtie over Chicago-sized 4326 coordinates
BOWTIE = Polygon([(-87.63, 41.78), (-87.62, 41.79), (-87.62, 41.78), (-87.63, 41.79)])


def test_heal_bowtie_with_injected_acceptance() -> None:
    assert not BOWTIE.is_valid
    seen: list[Polygon] = []

    def accepts(p: Polygon) -> bool:
        seen.append(p)
        return bool(p.is_valid)

    healed = heal(BOWTIE, accepts)
    assert healed is not None
    assert healed.geom_type == "Polygon" and healed.is_valid
    assert seen, "acceptance test was never consulted"
    assert healed.equals(seen[-1]), "returned candidate must be the accepted one"


def test_heal_returns_none_when_nothing_is_accepted() -> None:
    assert heal(BOWTIE, lambda _p: False) is None


def test_heal_returns_none_for_hopeless_geometry() -> None:
    """A zero-area collinear ring collapses on every rung, even if acceptance is lax.

    The points share a longitude, so the ring stays degenerate after the
    (nonlinear in latitude) Mercator transform too.
    """
    hopeless = Polygon([(-87.63, 41.78), (-87.63, 41.79), (-87.63, 41.785)])
    assert heal(hopeless, lambda _p: True) is None


# ------------------------------------------- widened mask convention ----

# the blank-core move (autogeoref.mask.move) detaches islands and punches
# holes, so everything downstream of the split must take MultiPolygon and
# holed masks

# ~100 m boxes in 4326 over Chicago; parts stay above SLIVER_AREA_M2 in 3857
MAIN_4326 = Polygon(
    [(-87.631, 41.781), (-87.628, 41.781), (-87.628, 41.784), (-87.631, 41.784)],
    holes=[[(-87.6302, 41.7822), (-87.6298, 41.7822), (-87.6298, 41.7826), (-87.6302, 41.7826)]],
)
ISLAND_4326 = box(-87.626, 41.782, -87.625, 41.783)
MULTI_HOLED_4326 = MAIN_4326.union(ISLAND_4326)


def test_snap_clean_preserves_multipart_and_holes() -> None:
    from autogeoref.mask.geometry import snap_clean

    assert MULTI_HOLED_4326.geom_type == "MultiPolygon"
    out = snap_clean(MULTI_HOLED_4326)
    assert out.geom_type == "MultiPolygon"
    assert len(out.geoms) == 2
    assert any(p.interiors for p in out.geoms), "the hole was filled"


def test_heal_multipart_holed_mask_with_injected_acceptance() -> None:
    healed = heal(MULTI_HOLED_4326, lambda p: p.is_valid)
    assert healed is not None
    assert healed.geom_type == "MultiPolygon"
    assert len(healed.geoms) == 2
    assert any(p.interiors for p in healed.geoms), "the hole was filled"


def test_multipart_and_holed_masks_survive_real_cutline_dryrun(
    p2_dryrun_context: tuple[Path, tuple[float, float, float, float]],
) -> None:
    """The REAL gdalwarp accepts island and holed cutlines — the feasibility
    gate required before the blank-core move could ship."""
    from shapely.geometry import MultiPolygon

    vrt, (minx, miny, maxx, maxy) = p2_dryrun_context
    w, h = maxx - minx, maxy - miny
    main = box(minx, miny, minx + 0.4 * w, maxy)
    island = box(minx + 0.7 * w, miny + 0.3 * h, minx + 0.9 * w, miny + 0.6 * h)
    hole = box(minx + 0.1 * w, miny + 0.4 * h, minx + 0.2 * w, miny + 0.5 * h)
    assert gdalwarp_cutline_dryrun(vrt, MultiPolygon([main, island])) is True
    assert gdalwarp_cutline_dryrun(vrt, box(minx, miny, maxx, maxy).difference(hole)) is True
    assert gdalwarp_cutline_dryrun(vrt, MultiPolygon([main.difference(hole), island])) is True


# --------------------------------------- validation is by gdalwarp, not IsValid ----


@pytest.fixture(scope="module")
def p2_dryrun_context(
    ground_truth_path: Path, vrt_dir: Path, sheet_vrt_cache: dict[str, Path]
) -> tuple[Path, tuple[float, float, float, float]]:
    slug = REF_SLUGS[0]
    image, fc = _case_inputs(slug, ground_truth_path)
    vrt = _sheet_vrt(slug, image, fc, vrt_dir, sheet_vrt_cache)
    with ground_truth_path.open() as f:
        layers = json.load(f)
    extent = next(x["extent"] for x in layers if x["slug"] == slug)
    return vrt, tuple(extent)


def test_shapely_valid_polygon_can_still_be_rejected_by_gdalwarp(
    p2_dryrun_context: tuple[Path, tuple[float, float, float, float]],
) -> None:
    """The verdict comes from the REAL gdalwarp, not shapely is_valid.

    A sub-pixel box is perfectly valid to shapely, but the real
    ``gdalwarp -crop_to_cutline`` cannot produce a raster from it and exits
    nonzero (measured on GDAL 3.8.4) — an IsValid-based check would wave it
    through.
    """
    vrt, (minx, miny, maxx, maxy) = p2_dryrun_context
    cx, cy = (minx + maxx) / 2, (miny + maxy) / 2
    tiny = box(cx, cy, cx + 1e-10, cy + 1e-10)
    assert tiny.is_valid
    assert gdalwarp_cutline_dryrun(vrt, tiny) is False


def test_hostile_but_valid_spike_goes_through_real_dryrun(
    p2_dryrun_context: tuple[Path, tuple[float, float, float, float]],
) -> None:
    """A shapely-valid near-degenerate spike is judged by gdalwarp itself."""
    vrt, (minx, miny, maxx, maxy) = p2_dryrun_context
    cx = (minx + maxx) / 2
    d = 1e-9  # near-zero-width spike poking past the sheet's top edge
    spike = Polygon(
        [
            (minx + 5e-4, miny + 5e-4),
            (maxx - 5e-4, miny + 5e-4),
            (maxx - 5e-4, maxy - 5e-4),
            (cx + d, maxy - 5e-4),
            (cx, maxy + 0.01),
            (cx - d, maxy - 5e-4),
            (minx + 5e-4, maxy - 5e-4),
        ]
    )
    assert spike.is_valid
    assert gdalwarp_cutline_dryrun(vrt, spike) is True


def test_invalid_pinch_is_rejected_by_real_dryrun(
    p2_dryrun_context: tuple[Path, tuple[float, float, float, float]],
) -> None:
    """A self-touching (pinched) ring is refused by the real warp (exit != 0)."""
    vrt, (minx, miny, maxx, maxy) = p2_dryrun_context
    cx, cy = (minx + maxx) / 2, (miny + maxy) / 2
    pinch = Polygon(
        [
            (minx + 5e-4, miny + 5e-4),
            (maxx - 5e-4, miny + 5e-4),
            (cx, cy),
            (maxx - 5e-4, maxy - 5e-4),
            (minx + 5e-4, maxy - 5e-4),
            (cx, cy),
        ]
    )
    assert not pinch.is_valid
    assert gdalwarp_cutline_dryrun(vrt, pinch) is False


def test_heal_with_real_gdalwarp_acceptance(
    p2_dryrun_context: tuple[Path, tuple[float, float, float, float]],
) -> None:
    """The heal ladder wired to the REAL dry-run rescues an invalid mask."""
    vrt, (minx, miny, maxx, maxy) = p2_dryrun_context
    bowtie = Polygon([(minx, miny), (maxx, maxy), (maxx, miny), (minx, maxy)])
    assert not bowtie.is_valid
    assert gdalwarp_cutline_dryrun(vrt, bowtie) is False
    healed = heal(bowtie, lambda p: gdalwarp_cutline_dryrun(vrt, p))
    assert healed is not None
    assert gdalwarp_cutline_dryrun(vrt, healed) is True
