"""Render the panels as the markdown page under ``docs/``.

The stepper and the markdown page carry the same step text, so both are written
from the panels the generator just built. Hand edits to the markdown are lost on
the next run.
"""

from __future__ import annotations

import os
import textwrap
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from walkthrough_page import Panel, State

#: Columns the prose is wrapped to, matching the rest of ``docs/``.
WIDTH = 80

#: How many plates a grid of extra states puts on one row.
GRID_COLUMNS = 3

#: Longest leading label ``_bolded_lead`` will bold, in words.
LEAD_WORDS = 3

NOTE = "### Note\n\n_This doc was generated by an LLM._"

TITLE = "# How a scanned atlas becomes a map"

INTRO = """The whole pipeline in {count} steps, following one volume: {title},
{sheets} sheets. Two of the steps need something that volume does not have (a
plainly misread sheet, and a volume a volunteer hand-placed) and name the atlas
they borrow in their own figures.

Every figure is rendered from a real run by
`scripts/walkthrough/make_walkthrough_assets.py`. Nothing is a mock-up and no
number is typed by hand: the generator calls the pipeline's own functions and
refuses to draw a page whose figures disagree with the record on disk.

The same walkthrough runs as a stepper at `/walkthrough.html` beside the map
viewer, where each panel's prepared states can be compared side by side. This
page is all of it in one scroll.

Two steps are told out of run order and say so where they appear. Thresholds
live with the modules that enforce them, and `docs/INTERNALS.md` carries the
detail behind the evidence vote."""

OUTRO = """## Regenerating this page

```sh
uv run python scripts/walkthrough/make_walkthrough_assets.py --work work
```

Input is a placed volume in gitignored `work/`; output is tracked, under
`viewer/walkthrough/`, because a cold clone cannot run the generator.
`scripts/walkthrough/walkthrough_exemplars.json` pins which volume and which
sheets it uses.

That same command writes this page, so edit the step text in
`scripts/walkthrough/walkthrough_*.py` and regenerate. Anything written here by
hand is lost on the next run.

{scan_credit}; {centerline_credit}."""


def _wrap_block(text: str) -> str:
    """Several paragraphs, each wrapped, blank lines kept. Fenced blocks pass through."""
    blocks = text.split("\n\n")
    return "\n\n".join(
        block if block.startswith("```") or "\n```" in block else _wrap(block) for block in blocks
    )


def _wrap(text: str, prefix: str = "") -> str:
    """One paragraph wrapped to ``WIDTH``, every line carrying ``prefix``."""
    return "\n".join(
        textwrap.wrap(
            " ".join(text.split()),
            width=WIDTH,
            initial_indent=prefix,
            subsequent_indent=prefix,
            break_long_words=False,
            break_on_hyphens=False,
        )
    )


def _sentence(text: str) -> str:
    """Upper-case the first letter only, leaving proper nouns alone."""
    return text[:1].upper() + text[1:]


def _cell(text: str) -> str:
    """Table-cell text with the one character that would split a row escaped."""
    return text.replace("|", "\\|")


def _bolded_lead(note: str) -> str:
    """Bold a short leading label, so the blockquote reads as an aside.

    A note with no colon, or one whose first colon is deep in a sentence, is
    left alone rather than emphasising an arbitrary clause.
    """
    lead, sep, rest = note.partition(":")
    if not sep or len(lead.split()) > LEAD_WORDS:
        return note
    return f"**{lead}:**{rest}"


def _image(state: State, alt: str, plates: str) -> str:
    return f"![{_cell(alt)}]({plates}/{state.file})"


def _row(cells: list[str]) -> str:
    return "| " + " | ".join(cells) + " |"


def _labelled(states: list[State], plates: str) -> list[str]:
    """Plates side by side, each under its own state label."""
    return [
        _row([_cell(s.label) for s in states]),
        _row(["---"] * len(states)),
        _row([_image(s, s.alt.rstrip("."), plates) for s in states]),
    ]


def _grid(states: list[State], plates: str) -> list[str]:
    """Plates in rows of ``GRID_COLUMNS``, with the last row padded out."""
    width = min(GRID_COLUMNS, len(states))
    lines = [_row([""] * width), _row(["---"] * width)]
    for start in range(0, len(states), GRID_COLUMNS):
        cells = [_image(s, s.alt.rstrip("."), plates) for s in states[start : start + GRID_COLUMNS]]
        lines.append(_row(cells + [""] * (width - len(cells))))
    return lines


def _figures(panel: Panel) -> list[str]:
    """The panel's measured values, the same pairs the stepper lists."""
    if not panel.figures:
        return []
    return [
        _row(["", ""]),
        _row(["---", "---"]),
        *(_row([_cell(label), _cell(value)]) for label, value in panel.figures),
        "",
    ]


def _panel(panel: Panel, plates: str) -> list[str]:
    """One step: its heading, its plates, its caption, its figures, any note."""
    lines = [f"### {panel.number}. {panel.title}", ""]
    states = panel.states
    if len(states) == 2:
        lines += [*_labelled(states, plates), ""]
    elif states:
        lines += [_image(states[0], states[0].alt.rstrip("."), plates), ""]
    lines += [_wrap(panel.caption), ""]
    if len(states) > 2:
        lines += [*_grid(states[1:], plates), ""]
    lines += _figures(panel)
    if panel.note:
        lines += [_wrap(_bolded_lead(panel.note), prefix="> "), ""]
    return lines


def _glossary(glossary: list[tuple[str, str]]) -> list[str]:
    """The same short word list the stepper offers."""
    if not glossary:
        return []
    return ["## A few words", "", *(_wrap(f"**{t}** {g}") for t, g in glossary), ""]


def render(
    meta: dict[str, Any],
    panels: list[Panel],
    glossary: list[tuple[str, str]],
    plates: str,
) -> str:
    """The whole page, ready to write. ``plates`` is the path the images sit under."""
    lines = [
        NOTE,
        "",
        TITLE,
        "",
        _wrap_block(INTRO.format(count=len(panels), title=meta["title"], sheets=meta["sheets"])),
        "",
    ]
    act = ""
    for panel in panels:
        if panel.act != act:
            act = panel.act
            lines += ["---", "", f"## {act}", ""]
        lines += _panel(panel, plates)
    lines += ["---", "", *_glossary(glossary), "---", ""]
    lines.append(
        _wrap_block(
            OUTRO.format(
                scan_credit=_sentence(meta["scan_credit"]),
                centerline_credit=meta["centerline_credit"],
            )
        )
    )
    return "\n".join(lines).rstrip("\n") + "\n"


def write_markdown(
    path: Path,
    *,
    meta: dict[str, Any],
    panels: list[Panel],
    glossary: list[tuple[str, str]],
    out: Path,
) -> None:
    """Write the page, pointing its images at wherever ``out`` put the plates."""
    plates = os.path.relpath(out.resolve(), path.resolve().parent).replace(os.sep, "/")
    path.write_text(render(meta, panels, glossary, plates), encoding="utf-8")
